// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.FamilyFeature;

public partial class FamilyMemberEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid FamilyId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual FamilyEntity Family { get; set; }

    public virtual ICollection<MemberRoleEntity> MemberRoleEntity { get; set; } = new List<MemberRoleEntity>();
}