// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.FamilyFeature;

public partial class MemberRoleEntity
{
    public Guid Id { get; set; }

    public Guid MemberId { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual FamilyMemberEntity Member { get; set; }

    public virtual FamilyRoleEntity Role { get; set; }
}