// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.Models;

public partial class RecipeEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Backstory { get; set; }

    public TimeSpan FinalTime { get; set; }

    public int Portions { get; set; }

    public Guid RecipeBookId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual RecipeBookEntity RecipeBook { get; set; }

    public virtual ICollection<RecipeIngredientEntity> RecipeIngredientEntity { get; set; } = new List<RecipeIngredientEntity>();

    public virtual ICollection<RecipeStepEntity> RecipeStepEntity { get; set; } = new List<RecipeStepEntity>();
}