// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Kin.KinHub.Core.Sql.Models;

public partial class CoreDbContext : DbContext
{
    public CoreDbContext(DbContextOptions<CoreDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FamilyEntity> FamilyEntity { get; set; }

    public virtual DbSet<FamilyMemberEntity> FamilyMemberEntity { get; set; }

    public virtual DbSet<FamilyRoleEntity> FamilyRoleEntity { get; set; }

    public virtual DbSet<FamilyService> FamilyService { get; set; }

    public virtual DbSet<KinHubService> KinHubService { get; set; }

    public virtual DbSet<MemberRoleEntity> MemberRoleEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FamilyEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyEntity");

            entity.ToTable("FamilyEntity", "core");

            entity.HasIndex(e => e.UserId, "IX_core_FamilyEntity_UserId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.AdminCodeHash).IsRequired();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<FamilyMemberEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyMemberEntity");

            entity.ToTable("FamilyMemberEntity", "core");

            entity.HasIndex(e => e.FamilyId, "IX_core_FamilyMemberEntity_FamilyId");

            entity.HasIndex(e => new { e.FamilyId, e.Name }, "UQ_core_FamilyMemberEntity_FamilyName").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Family).WithMany(p => p.FamilyMemberEntity)
                .HasForeignKey(d => d.FamilyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyMemberEntity_FamilyId");
        });

        modelBuilder.Entity<FamilyRoleEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyRoleEntity");

            entity.ToTable("FamilyRoleEntity", "core");

            entity.HasIndex(e => e.Name, "UQ_core_FamilyRoleEntity_Name").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<FamilyService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyService");

            entity.ToTable("FamilyService", "core");

            entity.HasIndex(e => e.FamilyId, "IX_core_FamilyService_FamilyId");

            entity.HasIndex(e => new { e.FamilyId, e.ServiceId }, "UQ_core_FamilyService_FamilyService").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Family).WithMany(p => p.FamilyService)
                .HasForeignKey(d => d.FamilyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyService_FamilyId");

            entity.HasOne(d => d.Service).WithMany(p => p.FamilyService)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyService_ServiceId");
        });

        modelBuilder.Entity<KinHubService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_KinHubService");

            entity.ToTable("KinHubService", "core");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BaseUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<MemberRoleEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_MemberRoleEntity");

            entity.ToTable("MemberRoleEntity", "core");

            entity.HasIndex(e => e.MemberId, "IX_core_MemberRoleEntity_MemberId");

            entity.HasIndex(e => new { e.MemberId, e.RoleId }, "UQ_core_MemberRoleEntity_MemberRole").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberRoleEntity)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_MemberRoleEntity_MemberId");

            entity.HasOne(d => d.Role).WithMany(p => p.MemberRoleEntity)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_MemberRoleEntity_RoleId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}