// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.Sql.Models;

public partial class FamilyEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid UserId { get; set; }

    public string AdminCodeHash { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<FamilyMemberEntity> FamilyMemberEntity { get; set; } = new List<FamilyMemberEntity>();

    public virtual ICollection<FamilyService> FamilyService { get; set; } = new List<FamilyService>();
}