// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.Sql.Models;

public partial class KinHubServiceEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string BaseUrl { get; set; }

    public bool IsActive { get; set; }

    public bool IsAdminOnly { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<FamilyServiceEntity> FamilyServiceEntity { get; set; } = new List<FamilyServiceEntity>();
}