// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Kin.KinHub.Identity.Sql.Models;

public partial class IdentityDbContext : DbContext
{
    public IdentityDbContext(DbContextOptions<IdentityDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ProviderEntity> ProviderEntity { get; set; }

    public virtual DbSet<RefreshTokenEntity> RefreshTokenEntity { get; set; }

    public virtual DbSet<UserCredentialEntity> UserCredentialEntity { get; set; }

    public virtual DbSet<KinUserEntity> UserEntity { get; set; }

    public virtual DbSet<UserProviderEntity> UserProviderEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ProviderEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_identity_ProviderEntity");

            entity.ToTable("ProviderEntity", "identity");

            entity.HasIndex(e => e.Name, "UQ_identity_ProviderEntity_Name").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<RefreshTokenEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_identity_RefreshTokenEntity");

            entity.ToTable("RefreshTokenEntity", "identity");

            entity.HasIndex(e => e.UserId, "IX_identity_RefreshTokenEntity_UserId");

            entity.HasIndex(e => e.Token, "UQ_identity_RefreshTokenEntity_Token").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(512);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokenEntity)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_identity_RefreshTokenEntity_UserId");
        });

        modelBuilder.Entity<UserCredentialEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_identity_UserCredentialEntity");

            entity.ToTable("UserCredentialEntity", "identity");

            entity.HasIndex(e => e.UserId, "UQ_identity_UserCredentialEntity_UserId").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.PasswordHash).IsRequired();

            entity.HasOne(d => d.User).WithOne(p => p.UserCredentialEntity)
                .HasForeignKey<UserCredentialEntity>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_identity_UserCredentialEntity_UserId");
        });

        modelBuilder.Entity<KinUserEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_identity_UserEntity");

            entity.ToTable("UserEntity", "identity");

            entity.HasIndex(e => e.Email, "UQ_identity_UserEntity_Email").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Active");
        });

        modelBuilder.Entity<UserProviderEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_identity_UserProviderEntity");

            entity.ToTable("UserProviderEntity", "identity");

            entity.HasIndex(e => new { e.ProviderId, e.ProviderUserId }, "UQ_identity_UserProviderEntity_ProviderUser").IsUnique();

            entity.HasIndex(e => new { e.UserId, e.ProviderId }, "UQ_identity_UserProviderEntity_UserProvider").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.ProviderUserId)
                .IsRequired()
                .HasMaxLength(256);

            entity.HasOne(d => d.Provider).WithMany(p => p.UserProviderEntity)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_identity_UserProviderEntity_ProviderId");

            entity.HasOne(d => d.User).WithMany(p => p.UserProviderEntity)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_identity_UserProviderEntity_UserId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}