// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Identity.Sql.Models;

public partial class KinUserEntity
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string DisplayName { get; set; }

    public bool IsEmailVerified { get; set; }

    public string Status { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<RefreshTokenEntity> RefreshTokenEntity { get; set; } = new List<RefreshTokenEntity>();

    public virtual UserCredentialEntity UserCredentialEntity { get; set; }

    public virtual ICollection<UserProviderEntity> UserProviderEntity { get; set; } = new List<UserProviderEntity>();
}