// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Identity.Sql.Models;

public partial class ProviderEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<UserProviderEntity> UserProviderEntity { get; set; } = new List<UserProviderEntity>();
}