// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Identity.Sql.Models;

public partial class UserProviderEntity
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public int ProviderId { get; set; }

    public string ProviderUserId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProviderEntity Provider { get; set; }

    public virtual KinUserEntity User { get; set; }
}