// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Kin.KinHub.Core.PostgreSql.Common;

public partial class CoreDbContext : DbContext
{
    public CoreDbContext(DbContextOptions<CoreDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FamilyEntity> FamilyEntity { get; set; }

    public virtual DbSet<FamilyMemberEntity> FamilyMemberEntity { get; set; }

    public virtual DbSet<FamilyRoleEntity> FamilyRoleEntity { get; set; }

    public virtual DbSet<FamilyServiceEntity> FamilyServiceEntity { get; set; }

    public virtual DbSet<FridgeEntity> FridgeEntity { get; set; }

    public virtual DbSet<FridgeIngredientEntity> FridgeIngredientEntity { get; set; }

    public virtual DbSet<KinHubServiceEntity> KinHubServiceEntity { get; set; }

    public virtual DbSet<MemberRoleEntity> MemberRoleEntity { get; set; }

    public virtual DbSet<RecipeBookEntity> RecipeBookEntity { get; set; }

    public virtual DbSet<RecipeEntity> RecipeEntity { get; set; }

    public virtual DbSet<RecipeIngredientEntity> RecipeIngredientEntity { get; set; }

    public virtual DbSet<RecipeStepEntity> RecipeStepEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("pg_catalog", "azure")
            .HasPostgresExtension("pg_catalog", "pgaadauth")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<FamilyEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyEntity");

            entity.ToTable("FamilyEntity", "core");

            entity.HasIndex(e => e.UserId, "IX_core_FamilyEntity_UserId");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.AdminCodeHash).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<FamilyMemberEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyMemberEntity");

            entity.ToTable("FamilyMemberEntity", "core");

            entity.HasIndex(e => e.FamilyId, "IX_core_FamilyMemberEntity_FamilyId");

            entity.HasIndex(e => new { e.FamilyId, e.Name }, "UQ_core_FamilyMemberEntity_FamilyName").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Family).WithMany(p => p.FamilyMemberEntity)
                .HasForeignKey(d => d.FamilyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyMemberEntity_FamilyId");
        });

        modelBuilder.Entity<FamilyRoleEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyRoleEntity");

            entity.ToTable("FamilyRoleEntity", "core");

            entity.HasIndex(e => e.Name, "UQ_core_FamilyRoleEntity_Name").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<FamilyServiceEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_FamilyServiceEntity");

            entity.ToTable("FamilyServiceEntity", "core");

            entity.HasIndex(e => e.FamilyId, "IX_core_FamilyServiceEntity_FamilyId");

            entity.HasIndex(e => new { e.FamilyId, e.ServiceId }, "UQ_core_FamilyServiceEntity_FamilyService").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Family).WithMany(p => p.FamilyServiceEntity)
                .HasForeignKey(d => d.FamilyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyServiceEntity_FamilyId");

            entity.HasOne(d => d.Service).WithMany(p => p.FamilyServiceEntity)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_FamilyServiceEntity_ServiceId");
        });

        modelBuilder.Entity<FridgeEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_FridgeEntity");

            entity.ToTable("FridgeEntity", "kinrecipe");

            entity.HasIndex(e => e.FamilyId, "IX_kinrecipe_FridgeEntity_FamilyId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<FridgeIngredientEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_FridgeIngredientEntity");

            entity.ToTable("FridgeIngredientEntity", "kinrecipe");

            entity.HasIndex(e => e.FridgeId, "IX_kinrecipe_FridgeIngredientEntity_FridgeId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.MeasureUnit)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Quantity).HasPrecision(18, 4);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Fridge).WithMany(p => p.FridgeIngredientEntity)
                .HasForeignKey(d => d.FridgeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kinrecipe_FridgeIngredientEntity_FridgeId");
        });

        modelBuilder.Entity<KinHubServiceEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_KinHubServiceEntity");

            entity.ToTable("KinHubServiceEntity", "core");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BaseUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<MemberRoleEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_core_MemberRoleEntity");

            entity.ToTable("MemberRoleEntity", "core");

            entity.HasIndex(e => e.MemberId, "IX_core_MemberRoleEntity_MemberId");

            entity.HasIndex(e => new { e.MemberId, e.RoleId }, "UQ_core_MemberRoleEntity_MemberRole").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberRoleEntity)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_MemberRoleEntity_MemberId");

            entity.HasOne(d => d.Role).WithMany(p => p.MemberRoleEntity)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_core_MemberRoleEntity_RoleId");
        });

        modelBuilder.Entity<RecipeBookEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_RecipeBookEntity");

            entity.ToTable("RecipeBookEntity", "kinrecipe");

            entity.HasIndex(e => e.FamilyId, "IX_kinrecipe_RecipeBookEntity_FamilyId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<RecipeEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_RecipeEntity");

            entity.ToTable("RecipeEntity", "kinrecipe");

            entity.HasIndex(e => e.RecipeBookId, "IX_kinrecipe_RecipeEntity_RecipeBookId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.Backstory).HasMaxLength(2000);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.RecipeBook).WithMany(p => p.RecipeEntity)
                .HasForeignKey(d => d.RecipeBookId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kinrecipe_RecipeEntity_RecipeBookId");
        });

        modelBuilder.Entity<RecipeIngredientEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_RecipeIngredientEntity");

            entity.ToTable("RecipeIngredientEntity", "kinrecipe");

            entity.HasIndex(e => e.RecipeId, "IX_kinrecipe_RecipeIngredientEntity_RecipeId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.MeasureUnit)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Quantity).HasPrecision(18, 4);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeIngredientEntity)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kinrecipe_RecipeIngredientEntity_RecipeId");
        });

        modelBuilder.Entity<RecipeStepEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_kinrecipe_RecipeStepEntity");

            entity.ToTable("RecipeStepEntity", "kinrecipe");

            entity.HasIndex(e => e.RecipeId, "IX_kinrecipe_RecipeStepEntity_RecipeId").HasFilter("(\"IsDeleted\" = false)");

            entity.Property(e => e.Id).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeStepEntity)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kinrecipe_RecipeStepEntity_RecipeId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}