// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kin.KinHub.Core.PostgreSql.RecipeFeature;

public partial class RecipeStepEntity
{
    public Guid Id { get; set; }

    public int Order { get; set; }

    public string Description { get; set; }

    public Guid RecipeId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual RecipeEntity Recipe { get; set; }
}